// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abhgwipckzoqardafoag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiaGd3aXBja3pvcWFyZGFmb2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3ODY1NDYsImV4cCI6MjA1MDM2MjU0Nn0.UWDXi7CDdJ6fbIr0iaZDgCa7WOmJv8aWUVSi1XGjPL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);